name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Log node version
        run: node -v

      - name: Install deps
        run: pnpm i
      
      - name: Run lint
        run: npm run lint